language: ruby
sudo: false
cache: bundler

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

before_install:
  - gem install bundler
  - bundler --version

before_script:
  - bundle update

script: bundle exec rake test

notifications:
  email: false
